### ISSUE TITLE
force quit the left player if the other quits

### ISSUE THREAD

**Issue by HarishTeens** [HarishTeens/rpsgames#1]
In multiplayer feature , if one player leaves the room the other player who stays in the room is not notified anything ,
- [ ] Force quit the user
- [ ] prompt user to switch to computer mode and resume in computer mode

**Comment by shravan-balasubramanian** [comment]
Is there any design for the prompt ? I need to work on this. Or can I go wild with the design?

**Comment by HarishTeens** [comment]
@shravan-balasubramanian  basic design would do, do it as you like
