### ISSUE TITLE
Better Chat UI

### ISSUE THREAD

**Issue by HarishTeens** [HarishTeens/rpsgames#2]
Submit a better chat UI for both desktop and Mobile view

**Comment by ChintanPalan** [comment]
Hey,
I would like to help here, Wanted to clear one thing before actually working on it.
Do we need the names of the sender and receiver in every message? Instead, we can write the name of other player in the top title bar and not mention the name of the current one at all?

**Comment by HarishTeens** [comment]
Sure , I think that would save a lot of space 
Go ahead @ChintanPalan

**Comment by ChintanPalan** [comment]
Cool, I will go ahead with it

**Comment by ChintanPalan** [comment]
Hey @HarishTeens 
Take a look at this and give your thoughts
This is the old UI:
![image](https://user-images.githubusercontent.com/19709183/67163020-db7c4600-f387-11e9-963a-1ee1cc881c2a.png)

This is the new one: 
![image](https://user-images.githubusercontent.com/19709183/67163023-e636db00-f387-11e9-80f3-4f58aa4a074a.png)

Whatsay?

**Comment by HarishTeens** [comment]
I love the new UI ❤️ , The old color scheme ain't good too ,so if you could do something about that .
And also send screenshots of the mobike view too

**Comment by ChintanPalan** [comment]
Cool, so will work on mobile tomorrow and send screenshots.

**Comment by ChintanPalan** [comment]
Even mobile UI is same, infact just got rid of most of the media queries and just adjusted the width of button a little but.
Here is a screenshot:
<img width="384" alt="Screenshot 2019-10-26 at 11 57 35 PM" src="https://user-images.githubusercontent.com/19709183/67624307-9d31cb80-f84c-11e9-9513-18f461b50a04.png">

**Comment by sed-lex** [comment]
Hello,

When the "joiner" joins the game, the "creator" chat is not updated and its opponent name is not displayed in the chatbox. In other words: only the "joiner" can see its opponent name in the chatbox.

It's easy to fix though.
